<a href="https://colab.research.google.com/github/2303a51690/23CSBTB27-28/blob/main/Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Creating Array and creating operation
import numpy as np
arr=np.array([2,4,6,9,14])
print(arr)
print(type(arr))

[ 2  4  6  9 14]
<class 'numpy.ndarray'>


In [6]:
import numpy as np
arr=np.array([[1,2],[3,6]])
print(arr)
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)
arr2=np.array([[1,2,9],[4,2,6],[7,8,9]])
print(arr1)
print(arr2)

[[1 2]
 [3 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 9]
 [4 2 6]
 [7 8 9]]
